global:
  resolve_timeout: 1m

route:
  group_by: ['alertname', 'category', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'lab-mailpit'

receivers:
- name: 'lab-mailpit'
  email_configs:
  - to: 'lab9@prodeng.local'
    from: 'alertmanager@prodeng.local'
    smarthost: mailpit:1025
    require_tls: false
    headers:
      subject: '[Lab 9] {{ .Status | toUpper }} - {{ .CommonLabels.alertname }}'
